openapi: 3.0.0
info:
  title: Memo App API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://api.memo-app.com/vv
tags:
  - name: users
    description: Operations about user
paths:
  /users:
    get:
      tags:
        - users
      operationId: getUsers
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Users'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{id}:
    get:
      tags:
        - users
      operationId: getUserById
      summary: Find user by ID
      description: Returns a single user
      parameters:
        - name: id
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
        data:
          type: object
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        id: 1
        name: user1
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
      example:
        - id: 1
          name: user1
        - id: 2
          name: user2
