name: generate code from openapi yaml

on:
  push:
    branches:
      - develop
    paths:
      - '**.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: honda-pp/memo-app-backend-go-gin
          path: generated
      - name: generate code
        uses: openapitools/openapi-generator-action@v1.0.0
        with:
          path: memo-app.yml
          generator: go-gin-server