name: generate code from openapi yaml

on:
  push:
    branches:
      - develop
    paths:
      - 'api/**.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: honda-pp/memo-app-backend-go-gin
          path: generated
      - name: generate code
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go-gin-server
          generator-tag: latest
          openapi-yaml: api/memo-app.yml